name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Compile Java files
        run: |
          javac -cp lib/junit-platform-console-standalone-1.8.2.jar src/TemperatureConverter.java test/TemperatureConverterTest.java

      - name: Run unit tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.8.2.jar --class-path src:test --scan-class-path

      - name: Autograding
        uses: education/autograding@v1